version: "3.9"

services:
  edge_postgresql:
    container_name: edge_postgresql
    image: bitnami/postgresql:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/bitnami/postgresql/data
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
