// import { RootProviders } from "@/lib/RootProviders";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RootProvider } from "@/lib/RootProvider";
import { cn } from "@/lib/utils/cn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "h-screen w-screen")}>
        <RootProvider>
          <main className="min-h-screen bg-background text-foreground">{children}</main>
        </RootProvider>
      </body>
    </html>
  );
}
